# Generated by Django 3.2.13 on 2023-01-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('std', models.IntegerField()),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Banglaore', 'Banglaore'), ('Hyderabad', 'Hyderabad'), ('Chennai', 'Chennai'), ('Mysore', 'Mysore')], max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
