# Generated by Django 3.2.13 on 2023-01-05 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='passout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
