# Generated by Django 3.2.13 on 2023-01-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
