# Generated by Django 3.2.13 on 2023-01-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='desc',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='code',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
