# Generated by Django 3.2.13 on 2023-01-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20230109_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ratings', models.IntegerField()),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
